"use client";

import { Check, History, LogOut, UtensilsCrossed } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { ActivityEvent, Order, OrderStatus } from "@/lib/types";

export default function OwnerDashboard() {
  const router = useRouter(); const [orders, setOrders] = useState<Order[]>([]); const [events, setEvents] = useState<ActivityEvent[]>([]); const [view, setView] = useState<"orders" | "history">("orders"); const [checked, setChecked] = useState<Record<string, boolean>>({});
  const load = async () => { const [a, b] = await Promise.all([fetch("/api/orders", { cache: "no-store" }), fetch("/api/history", { cache: "no-store" })]); if (a.status === 401) { router.replace("/order/table-1"); return; } setOrders((await a.json()).orders || []); if (b.ok) setEvents((await b.json()).events || []); };
  useEffect(() => { load(); const timer = window.setInterval(load, 3000); return () => window.clearInterval(timer); }, []);
  const patch = async (id: string, status?: OrderStatus, acknowledged?: boolean) => { await fetch(`/api/orders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, acknowledged }) }); await load(); };
  const units = (order: Order) => order.items.flatMap((item) => Array.from({ length: item.quantity }, (_, index) => ({ id: `${order.id}-${item.id}-${index}`, name: item.menuName })));
  const toggle = async (order: Order, id: string, value: boolean) => { const next = { ...checked, [id]: value }; setChecked(next); if (units(order).every((unit) => next[unit.id])) { await patch(order.id, undefined, true); const remaining = { ...next }; units(order).forEach((unit) => delete remaining[unit.id]); setChecked(remaining); } };
  const pending = orders.filter((order) => order.status === "pending"); const active = orders.filter((order) => ["accepted", "preparing"].includes(order.status) && !order.acknowledged);
  return <main className="simple-owner-shell"><header className="simple-owner-header"><div><span className="simple-brand"><UtensilsCrossed size={17} /> 주문해라</span><h1>{view === "orders" ? "주문 확인" : "히스토리"}</h1></div><button onClick={() => router.replace("/order/table-1")}><LogOut size={18} /></button></header><nav className="simple-owner-nav"><button className={view === "orders" ? "active" : ""} onClick={() => setView("orders")}>주문 {pending.length}</button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")}><History size={14} />히스토리</button></nav>{view === "orders" ? <section className="simple-orders">{pending.map((order) => <article className="simple-order-card pending" key={order.id}><header><b>테이블 {order.tableNumber}</b><time>{new Date(order.createdAt).toLocaleTimeString("ko-KR", { hour: "2-digit", minute: "2-digit" })}</time></header>{order.items.map((item) => <p key={item.id}>{item.menuName} × {item.quantity}</p>)}{order.note && <small>요청사항 · {order.note}</small>}<footer><button onClick={() => patch(order.id, "rejected", true)}>거절</button><button className="accept" onClick={() => patch(order.id, "accepted", false)}>주문 수락</button></footer></article>)}{active.map((order) => <article className="simple-order-card checking" key={order.id}><header><b>테이블 {order.tableNumber}</b><span>수락됨</span></header><ul>{units(order).map((unit) => <li className={checked[unit.id] ? "done" : ""} key={unit.id}><label><input type="checkbox" checked={Boolean(checked[unit.id])} onChange={(event) => toggle(order, unit.id, event.target.checked)} /><span>{unit.name}</span></label></li>)}</ul></article>)}{!pending.length && !active.length && <p className="simple-empty"><Check size={18} />확인할 주문이 없습니다.</p>}</section> : <section className="simple-history"><h2>전체 기록</h2>{events.length ? events.map((event) => <article key={event.id}><div><b>{event.type === "order_created" ? "주문 접수" : event.type === "payment_completed" ? "결제" : event.type === "tables_merged" ? "합석" : "합석 해제"}</b><span>{event.summary}</span></div><time>{new Date(event.createdAt).toLocaleString("ko-KR", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</time></article>) : <p className="simple-empty">아직 기록이 없습니다.</p>}</section>}</main>;
}

